FROM rust:latest AS builder
WORKDIR /app
COPY . .
RUN cargo build --release --bin topaz
RUN strip target/release/topaz

FROM debian:12-slim AS runtime
COPY --from=builder /app/target/release/topaz /bin/topaz
ENTRYPOINT ["/bin/topaz"]