name = "luau-worker"
type = "rust"
workers_dev = true
compatibility_date = "2022-01-20"

[vars]
WORKERS_RS_VERSION = "0.0.9"
AUTH_SECRET = "JRxwJlG8AA8xiSmd6JWFWI56b4ForVMbEMHwrXTyF65rKy0ZvhuhCfifZSSOeqFZ"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration