[package]
name = "topaz-gui"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
eframe = "0.31"
cfg = { path = "../cfg" }
lua51-lifter = { path = "../lua51-lifter" }
luau-lifter = { path = "../luau-lifter" }
rfd = "0.15"
axum = "0.8"
base64 = "0.22"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.42", features = ["rt", "net", "sync", "macros"] }
