name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Cache cargo registry & build artifacts
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --workspace --exclude topaz-gui --exclude luau-worker

      - name: Run tests
        run: cargo test --workspace --exclude topaz-gui --exclude luau-worker --verbose
